name: neelix
main: net.llgava.Neelix
version: ${version}
description: A Java library to avoid repetitive work while developing Minecraft Spigot/Paper plugins.
api-version: 1.13
author: Leonardo '_Fyat' Gava
