# An example of custom file (yes, the comments are copied too!)
my-plugin-is-amazing: true
locked-slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]
